#!/bin/sh
#
# Project        : PDBMap 
# Filename       : cluster_coefficient_updated.qsub
# Author         : R. Michael Sivley
# Organization   : Center for Human Genetics Research,
#                : Department of Biomedical Informatics,
#                : Vanderbilt University Medical Center
# Email          : mike.sivley@vanderbilt.edu
# Date           : 2014-08-13
# Description    : Calculated clustering coefficients for all structures/models
#                : Launch with: qsub -t0-$(P-1) -vPART=$P
#                : where $P is the maximum number of partitions/processes
#=============================================================================#
# PBS Parameters
#PBS -M mike.sivley@vanderbilt.edu
#PBS -m bae
#PBS -N 1kg_cluster_coefficient
#PBS -l nodes=1:ppn=1
#PBS -l mem=5000mb
#PBS -l walltime=1:00:00:00
#=============================================================================#

cd /projects/Bush_eQTL/sivleyrm/projects/pdbmap/scripts
./cluster_coefficient.py 1kg ${PART} ${PBS_ARRAYID}
