#!/bin/sh
#
# Project        : PDBMap 
# Filename       : load_everything.qsub
# Author         : R. Michael Sivley
# Organization   : Center for Human Genetics Research,
#                : Department of Biomedical Informatics,
#                : Vanderbilt University Medical Center
# Email          : mike.sivley@vanderbilt.edu
# Date           : 2014-03-12
# Description    : Loads all UniProt IDs into PDBMap, all 1000 Genomes v3
#                : variants, and intersects them.
#=============================================================================#
# PBS Parameters
#PBS -M mike.sivley@vanderbilt.edu
#PBS -N PDBMapMAFDecay
#PBS -m bae
#PBS -l mem=10000mb
#PBS -l walltime=2:00:00:00
#=============================================================================#

cd /projects/Bush_eQTL/sivleyrm/projects/pdbmap;
python27 scripts/freq_decay.py 1kg 1> temp/freq_decay.out 2> temp/freq_decay.err
python27 scripts/freq_decay.py esp 1> temp/freq_decay.out 2> temp/freq_decay.err
