#!/bin/sh
#
# Project        : PDBMap 
# Filename       : load_everything.qsub
# Author         : R. Michael Sivley
# Organization   : Center for Human Genetics Research,
#                : Department of Biomedical Informatics,
#                : Vanderbilt University Medical Center
# Email          : mike.sivley@vanderbilt.edu
# Date           : 2014-03-12
# Description    : Loads all UniProt IDs into PDBMap, all 1000 Genomes v3
#                : variants, and intersects them.
#=============================================================================#
# PBS Parameters
#PBS -M mike.sivley@vanderbilt.edu
#PBS -m bae
#PBS -l nodes=cottage.mc.vanderbilt.edu:ppn=20
#PBS -l mem=150000mb
#PBS -l walltime=10:00:00:00
#PBS -N PDBMap_Build_Pipeline
#=============================================================================#

cd /projects/Bush_eQTL/sivleyrm/projects/pdbmap;
# echo "Beginning load_unp..."
# PART=20
# for IDX in $(seq 0 $((PART-1)))
# do
#   echo "./pdbmap.py -c config/v10.config --ppart=$PART --ppidx=$IDX --slabel=uniprot-pdb load_unp >> temp/pdbmap-v10.out 2>> temp/pdbmap-v10.err &"
#   ./pdbmap.py -c config/v10.config --ppart=$PART --ppidx=$IDX --slabel=uniprot-pdb load_unp >> temp/pdbmap-v10.out 2>> temp/pdbmap-v10.err &
# done
# wait # for all background processes to finish
# echo "Finished load_unp"

# begin loading data

echo "Beginning load_data carissa..."
./pdbmap.py -c config/v10.config --slabel=uniprot-pdb --dlabel=carissa load_data data/carissa/coxph_exomechip_blacksonly_reducedAFRMode_n301_top10burdenGenes_top10SKATgenes_individSNPanalysis_noMA_gene-chr-bppos_05222014.bed >> temp/pdbmap-v10-carissa.out 2>> temp/pdbmap-v10-carissa.err &
echo "Finished load_data carissa"

echo "Beginning load_data gwas..."
./pdbmap.py -c config/v10.config --slabel=uniprot-pdb --dlabel=gwas load_data data/gwas/nhgri_gwas_catalog.bed > temp/pdbmap-v10-gwas.out 2> temp/pdbmap-v10-gwas.err &
echo "Finished load_data gwas"

echo "Beginning load_data humsavarcf..."
./pdbmap.py -c config/v10.config --slabel=uniprot-pdb --dlabel=humsavarcf load_data data/cf/humsavar/humsavarcf_hg19.bed > temp/pdbmap-v10-humsavarcf.out 2> temp/pdbmap-v10-humsavarcf.err &
echo "Finished load_data humsavarcf"

wait # before intersecting

echo "Beginning intersect carissa uniprot-pdb..."
./pdbmap.py -c config/v10.config intersect carissa uniprot-pdb 93 >> temp/pdbmap-v10-carissa.out 2>> temp/pdbmap-v10-carissa.err &
echo "Finished intersect carissa uniprot-pdb"

echo "Beginning intersect gwas uniprot-pdb..."
./pdbmap.py -c config/v10.config intersect gwas uniprot-pdb 17025 >> temp/pdbmap-v10-gwas.out 2>> temp/pdbmap-v10-gwas.err &
echo "Finished intersect gwas uniprot-pdb"

echo "Beginning intersect humsavarcf uniprot-pdb..."
./pdbmap.py -c config/v10.config intersect humsavarcf uniprot-pdb 127 >> temp/pdbmap-v10-humsavarcf.out 2>> temp/pdbmap-v10-humsavarcf.err &
echo "Finished intersect humsavarcf uniprot-pdb"

wait # before loading 1000 genomes

echo "Beginning load_data 1kg..."
for f in data/1kg/vcf/ALL.chr*.phase1_release_v3.20101123.snps_indels_svs.genotypes.vcf.gz;
do
  echo "./pdbmap.py -c config/v10.config --slabel=uniprot-pdb --dlabel=1kg load_data $f >> temp/pdbmap-v10-1kg.out 2>> temp/pdbmap-v10-1kg.err &"
  ./pdbmap.py -c config/v10.config --slabel=uniprot-pdb --dlabel=1kg load_data $f >> temp/pdbmap-v10-1kg.out 2>> temp/pdbmap-v10-1kg.err &
done
wait # for all background processes to finish
echo "Finished load_data 1kg"

echo "Beginning intersect 1kg uniprot-pdb..."
./pdbmap.py -c config/v10.config intersect 1kg uniprot-pdb >> temp/pdbmap-v10-1kg.out 2>> temp/pdbmap-v10-1kg.err
echo "Finished intersect 1kg uniprot-pdb"

echo "Beginning load_data esp..."
for f in data/esp/ESP6500SI-V2-SSA137.updatedProteinHgvs.chr*.snps_indels.vcf;
do
  echo "./pdbmap.py -c config/v10.config --slabel=uniprot-pdb --dlabel=esp load_data $f >> temp/pdbmap-v10-esp.out 2>> temp/pdbmap-v10-esp.err &"
  ./pdbmap.py -c config/v10.config --slabel=uniprot-pdb --dlabel=esp load_data $f >> temp/pdbmap-v10-esp.out 2>> temp/pdbmap-v10-esp.err &
done
wait # for all background processes to finish
echo "Finished load_data esp"

echo "Beginning intersect esp uniprot-pdb..."
./pdbmap.py -c config/v10.config intersect esp uniprot-pdb >> temp/pdbmap-v10-esp.out 2>> temp/pdbmap-v10-esp.err
echo "Finished intersect esp uniprot-pdb"

echo "Finished load_everything.qsub"
