#!/bin/sh
#
# Project        : PDBMap 
# Filename       : load_everything.qsub
# Author         : R. Michael Sivley
# Organization   : Center for Human Genetics Research,
#                : Department of Biomedical Informatics,
#                : Vanderbilt University Medical Center
# Email          : mike.sivley@vanderbilt.edu
# Date           : 2014-03-12
# Description    : Loads MetaboChip missense SNPs into PDBMap
#=============================================================================#
# PBS Parameters
#PBS -M mike.sivley@vanderbilt.edu
#PBS -N PDBMap-MetaboChip
#PBS -m bae
#PBS -l nodes=1:ppn=1
#PBS -l mem=15000mb
#PBS -l walltime=2:00:00:00
#=============================================================================#

cd /projects/Bush_eQTL/sivleyrm/projects/pdbmap;
./pdbmap.py -c config/v10.config --slabel=uniprot-pdb --dlabel=metabochip load_data data/metabochip/MetaboChip.markers.ncbi37.20101203.vcf.gz >> temp/pdbmap-v10-metabochip.out 2>> temp/pdbmap-v10-metabochip.err
./pdbmap.py -c config/v10.config intersect metabochip uniprot-pdb >> temp/pdbmap-v10-metabochip.out 2>> temp/pdbmap-v10-metabochip.err
