 #!/bin/bash -e
 vcftools/bin/vcftools \
--gzvcf /dors/capra_lab/data/1kg/vcf/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5.20130502.genotypes.vcf.gz \
--weir-fst-pop <(grep AMR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep EAS /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--stdout | vcftools/bin/vcftools --gzvcf - \
--weir-fst-pop <(grep AMR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep SAS /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--stdout | vcftools/bin/vcftools --gzvcf - \
--weir-fst-pop <(grep AMR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep EUR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--stdout | vcftools/bin/vcftools --gzvcf - \
--weir-fst-pop <(grep AMR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep AFR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--stdout | vcftools/bin/vcftools --gzvcf - \
--weir-fst-pop <(grep EAS /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep SAS /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--stdout | vcftools/bin/vcftools --gzvcf - \
--weir-fst-pop <(grep EAS /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep EUR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--stdout | vcftools/bin/vcftools --gzvcf - \
--weir-fst-pop <(grep EAS /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep AFR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--stdout | vcftools/bin/vcftools --gzvcf - \
--weir-fst-pop <(grep SAS /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep EUR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--stdout | vcftools/bin/vcftools --gzvcf - \
--weir-fst-pop <(grep SAS /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep AFR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--stdout | vcftools/bin/vcftools --gzvcf - \
--weir-fst-pop <(grep EUR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep AFR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--stdout | vcftools/bin/vcftools --gzvcf - \
--weir-fst-pop <(grep AMR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep EAS /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep SAS /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep EUR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--weir-fst-pop <(grep AFR /dors/capra_lab/data/1kg/vcf/integrated_call_samples_v3.20130502.ALL.panel) \
--stdout